import type { Idea, Feedback } from '@/types'

export const MOCK_IDEAS: Idea[] = [
  {
    id: 'idea-1',
    title: 'AI destekli Türkçe hukuk asistanı',
    description: 'Avukat ücretlerini karşılayamayanlar için yapay zeka ile sözleşme analizi, dava özeti ve basit hukuki tavsiye veren bir platform. Kullanıcı belge yükler, AI risk noktalarını işaretler.',
    category: 'teknoloji',
    tags: ['ai', 'hukuk', 'saas'],
    user_id: 'user-1',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: 'active',
    feedback_count: 4,
  },
  {
    id: 'idea-2',
    title: 'Mahalle esnafı için dijital menü ve sipariş sistemi',
    description: 'QR kod ile masa başından sipariş, küçük lokantalar ve kafeler için aylık 200 TL\'ye tüm dijital altyapı. POS entegrasyonu, stok takibi ve günlük rapor dahil.',
    category: 'iş',
    tags: ['pos', 'restoran', 'qr'],
    user_id: 'user-2',
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: 'active',
    feedback_count: 6,
  },
  {
    id: 'idea-3',
    title: 'Üniversite öğrencileri için ders notu paylaşım marketplace',
    description: 'Öğrenciler aldıkları notları satar, diğerleri satın alır. Hoca bazlı kategorileme, özet ve flashcard üretimi. Notların kalitesi öğrenci topluluğu tarafından oylanır.',
    category: 'eğitim',
    tags: ['eğitim', 'marketplace', 'öğrenci'],
    user_id: null,
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    status: 'active',
    feedback_count: 3,
  },
  {
    id: 'idea-4',
    title: 'Sokak hayvanları için konum tabanlı mama noktası ağı',
    description: 'Gönüllüler mama noktası oluşturur, ihtiyaç bildirimleri anlık bildirim olarak gelir. Bağış sistemi ile şehir genelinde koordineli besleme. Belediyelerle entegrasyon hedefi.',
    category: 'sosyal',
    tags: ['hayvan', 'gönüllü', 'sosyal'],
    user_id: 'user-1',
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    status: 'active',
    feedback_count: 8,
  },
  {
    id: 'idea-5',
    title: 'Bağımsız müzisyenler için Türkiye\'ye özel streaming + merch platform',
    description: 'Spotify\'da kaybolmak yerine kendi hayran kitlesine doğrudan sat. Dinleme + konser bileti + merch tek platformda. Gelirin %85\'i sanatçıya kalır.',
    category: 'sanat',
    tags: ['müzik', 'sanatçı', 'streaming'],
    user_id: 'user-2',
    created_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    status: 'active',
    feedback_count: 5,
  },
  {
    id: 'idea-6',
    title: 'Sağlıklı ofis yemeği için haftalık abonelik servisi',
    description: 'Kurumsal çalışanlara haftalık 5 gün öğle yemeği aboneliği. Diyetisyen onaylı menü, makro bilgisi, kişisel diyet tercihleri. B2B model, şirket HR\'a tek fatura.',
    category: 'sağlık',
    tags: ['yemek', 'kurumsal', 'abonelik'],
    user_id: null,
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    status: 'active',
    feedback_count: 2,
  },
  {
    id: 'idea-7',
    title: 'Türkçe stand-up komedi için online bilet + içerik platformu',
    description: 'Bağımsız stand-up sanatçıları show biletlerini satar, özel setlerini ücretli yayınlar. İzleyici puanlama sistemi, sanatçı profilleri, şehir bazlı etkinlik takvimi.',
    category: 'eğlence',
    tags: ['standup', 'bilet', 'komedi'],
    user_id: 'user-1',
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    status: 'active',
    feedback_count: 7,
  },
  {
    id: 'idea-8',
    title: 'Emekliler için dijital okuryazarlık koçluğu uygulaması',
    description: '60+ yaş için dokunmatik ekran odaklı, sade arayüzlü teknoloji eğitim uygulaması. WhatsApp, e-devlet, online bankacılık konularında adım adım rehberler ve video dersler.',
    category: 'diğer',
    tags: ['eğitim', 'yaşlı', 'dijital'],
    user_id: 'user-2',
    created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    status: 'active',
    feedback_count: 9,
  },
]

export const MOCK_FEEDBACKS: Feedback[] = [
  // idea-1 feedbacks
  {
    id: 'fb-1',
    idea_id: 'idea-1',
    strengths: 'Hukuki erişim sorunu gerçek. Büyük pazar var. AI maliyetleri düşük.',
    weaknesses: 'Yanlış hukuki tavsiye ciddi sorumluluk riski. Baro ile çatışma garantili.',
    suggestions: 'Tavsiye değil, bilgi platform olarak konumlan. "Bu avukatınızın işi" diyen sorumluluk reddi ile başla.',
    user_id: null,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    vote_counts: { up: 12, down: 2 },
    user_vote: null,
  },
  {
    id: 'fb-2',
    idea_id: 'idea-1',
    strengths: 'Sözleşme analizi kısmı güçlü. İşletmeler için değer net.',
    weaknesses: 'Türkçe hukuk verisi kısıtlı. Model eğitimi zor ve pahalı.',
    suggestions: 'Önce belirli bir alanda derin ol: sadece kira sözleşmeleri veya iş hukuku. Genele gitme.',
    user_id: 'user-2',
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    vote_counts: { up: 8, down: 1 },
    user_vote: null,
  },
  {
    id: 'fb-3',
    idea_id: 'idea-1',
    strengths: 'Freemium model uygun. Ölçeklenebilir.',
    weaknesses: 'Rakip çok. ChatGPT zaten bunu yapıyor ücretsiz.',
    suggestions: 'Baro ile iş ortaklığı kur. Avukat yönlendirme komisyonu al.',
    user_id: null,
    created_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    vote_counts: { up: 5, down: 3 },
    user_vote: null,
  },
  {
    id: 'fb-4',
    idea_id: 'idea-1',
    strengths: 'Rakipsiz değer önerisi var KOBİ segmentinde.',
    weaknesses: 'KVKK ve müvekkil gizliliği sorunları çözümsüz bırakılmış.',
    suggestions: 'Hukuki geçerlilik için bir danışman avukatla ortak ol. MVP\'yi hukuk fakülteleriyle test et.',
    user_id: 'user-1',
    created_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    vote_counts: { up: 15, down: 0 },
    user_vote: null,
  },
  // idea-2 feedbacks
  {
    id: 'fb-5',
    idea_id: 'idea-2',
    strengths: 'Fiyat rekabetçi. Sorun gerçek, pazar büyük.',
    weaknesses: 'İşletme sahiplerinin dijital adaptasyonu zor. Satış dönüşümü düşük olur.',
    suggestions: 'İlk 3 ay ücretsiz ver. Kurulumu sen git yap. Bağımlılık oluştuktan sonra ücret al.',
    user_id: null,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    vote_counts: { up: 20, down: 1 },
    user_vote: null,
  },
  {
    id: 'fb-6',
    idea_id: 'idea-2',
    strengths: 'QR menü COVID\'den beri kabul gördü. Müşteri alışkanlığı var.',
    weaknesses: 'Çok kalabalık pazar. ikas, Adisyo, Garson zaten var.',
    suggestions: 'Tek özellikle farklılaş: örneğin sadece WhatsApp sipariş entegrasyonu. Bunu kimse iyi yapmıyor.',
    user_id: 'user-1',
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    vote_counts: { up: 11, down: 4 },
    user_vote: null,
  },
  // idea-4 feedbacks
  {
    id: 'fb-7',
    idea_id: 'idea-4',
    strengths: 'Gönüllü motivasyonu yüksek. Duygusal bağ güçlü.',
    weaknesses: 'Monetizasyon yok. Sürdürülebilirlik sorunlu. Gönüllü yorgunluğu gerçek.',
    suggestions: 'Belediye ihalesi modeli dene. Belediyelerin zaten bu harcamaları var, sen koordinasyonu yap.',
    user_id: null,
    created_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    vote_counts: { up: 25, down: 2 },
    user_vote: null,
  },
  {
    id: 'fb-8',
    idea_id: 'idea-4',
    strengths: 'Topluluk etkisi güçlü. Viral potansiyeli var.',
    weaknesses: 'Spam ve sahte nokta riski. Moderasyon masrafı artar.',
    suggestions: 'Hayvan barınaklarıyla entegre ol. Sahiplenmeye yönlendirme ekle.',
    user_id: 'user-2',
    created_at: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    vote_counts: { up: 18, down: 0 },
    user_vote: null,
  },
]

export const MOCK_PROFILES = [
  { id: 'user-1', username: 'ahmet_k', created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'user-2', username: 'zeynep_d', created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString() },
]
